services:
  api:
    build: .
    container_name: diabetes_api
    command: uvicorn src.app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app

  streamlit:
    build: .
    container_name: diabetes_ui
    command: streamlit run src/app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_URL=http://api:8000/predict
    depends_on:
      - api